# Form implementation generated from reading ui file '../Modules/nqrduck-measurement/src/nqrduck_measurement/resources/measurement_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonStart = QtWidgets.QPushButton(parent=Form)
        self.buttonStart.setObjectName("buttonStart")
        self.verticalLayout_2.addWidget(self.buttonStart)
        self.labelSpectrometer = QtWidgets.QLabel(parent=Form)
        self.labelSpectrometer.setObjectName("labelSpectrometer")
        self.verticalLayout_2.addWidget(self.labelSpectrometer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotter = MplWidget(parent=Form)
        self.plotter.setObjectName("plotter")
        self.verticalLayout.addWidget(self.plotter)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buttonStart.setText(_translate("Form", "Start Measurement"))
        self.labelSpectrometer.setText(_translate("Form", "Spectrometer:"))

from nqrduck.contrib.mplwidget import MplWidget
