# Form implementation generated from reading ui file '../Modules/nqrduck-measurement/src/nqrduck_measurement/resources/measurement_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settingsLayout = QtWidgets.QVBoxLayout()
        self.settingsLayout.setObjectName("settingsLayout")
        self.titleLable = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLable.setFont(font)
        self.titleLable.setObjectName("titleLable")
        self.settingsLayout.addWidget(self.titleLable)
        self.spectrometerLayout = QtWidgets.QHBoxLayout()
        self.spectrometerLayout.setObjectName("spectrometerLayout")
        self.spectrometerLabel = QtWidgets.QLabel(parent=Form)
        self.spectrometerLabel.setObjectName("spectrometerLabel")
        self.spectrometerLayout.addWidget(self.spectrometerLabel)
        self.settingsLayout.addLayout(self.spectrometerLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.settingsLayout.addLayout(self.gridLayout)
        self.buttonStart = QtWidgets.QPushButton(parent=Form)
        self.buttonStart.setObjectName("buttonStart")
        self.settingsLayout.addWidget(self.buttonStart)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.settingsLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.settingsLayout)
        self.plotterLayout = QtWidgets.QVBoxLayout()
        self.plotterLayout.setObjectName("plotterLayout")
        self.plotter = MplWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotter.sizePolicy().hasHeightForWidth())
        self.plotter.setSizePolicy(sizePolicy)
        self.plotter.setObjectName("plotter")
        self.plotterLayout.addWidget(self.plotter)
        self.horizontalLayout_2.addLayout(self.plotterLayout)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLable.setText(_translate("Form", "Single Frequency Measurement: "))
        self.spectrometerLabel.setText(_translate("Form", "Spectrometer:"))
        self.label.setText(_translate("Form", "Target Frequency"))
        self.label_2.setText(_translate("Form", "Averages"))
        self.buttonStart.setText(_translate("Form", "Start Measurement"))
from nqrduck.contrib.mplwidget import MplWidget
